version: '3.3'

services:

  keystore:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    command: bash /setup/setup-keystore.sh
    volumes:
        - ${ELASTIC_DATA}/secrets:/secrets/
        - ${ELASTIC_DATA}/setup/:/setup/
    user: "0"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ${ELASTIC_DATA}/secrets:/secrets/
      - ${ELASTIC_DATA}/setup/:/setup/
